services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    env_file:
      - .env
    networks:
      jenkins-net:
    ports:
      - "8080:8080"
      - "50000:50000"
      - "22:22"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID:-admin}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-admin}
      - JENKINS_URL=http://localhost:8080/${JENKINS_CONTROLLER_PREFIX}
      - JENKINS_OPTS="--prefix=/${JENKINS_CONTROLLER_PREFIX}"
      - JENKINS_SSH_PRIVATE_KEY=${JENKINS_SSH_PRIVATE_KEY}

  jenkins-agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    networks:
      jenkins-net:
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
